language: objective-c
osx_image: xcode9.1
xcode_workspace: IconMan.xcworkspace
xcode_scheme: IconMan
before_install:
- gem install cocoapods
- pod repo update --silent
script: xcodebuild -workspace IconMan.xcworkspace -scheme IconMan CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
