language: objective-c
osx_image: xcode8.2
xcode_workspace: IconMan.xcworkspace
xcode_scheme: IconMan
before_install:
- gem install activesupport -v 4.2.6
- gem install cocoapods
- pod repo update --silent
script: xcodebuild -workspace IconMan.xcworkspace -scheme IconMan CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
